name: GitHub Actions Automatic Deployment
on: push
jobs:
  deployment-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          # ssh-keyscan -H 172.93.40.89
          echo "${{ secrets.W8_SSH_HOST }}" >> ~/.ssh/known_hosts
          # ssh-keyscan -p 28714 98.142.143.114
          echo "${{ secrets.CAL_SSH_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SEL_SSH_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SGP1_SSH_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.TKY_SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          echo '--------------------- w8 ----------------------'
          # ssh azureuser@20.212.234.243 "./deploy.sh"
          echo '--------------------- cal ---------------------'
          # ssh root@172.93.43.102 -p 28714 "./deploy.sh"
          echo '--------------------- sel ---------------------'
          # ssh ubuntu@131.186.26.3 "./deploy.sh"
          echo '--------------------- sgp1 ---------------------'
          # ssh azureuser@52.230.104.42 "./deploy.sh"
          echo '--------------------- tky ---------------------'
          # ssh ubuntu@43.207.76.168 "./deploy.sh"
