name: GitHub Actions Automatic Deployment
on: push
jobs:
  deployment-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          # ssh-keyscan -H 172.93.40.89
          echo "${{ secrets.SSHED_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.RM_SSH_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.W82ND_SSH_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SL_SSH_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SG_SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          echo '--------------------- w8 ---------------------'
          ssh caster@34.96.219.248 "./deploy.sh"
          echo '--------------------- rm ---------------------'
          ssh root@172.93.40.89 -p 28714 "./deploy.sh"
          # echo '--------------------- w82nd ---------------------'
          # ssh caster@20.239.161.41 "./deploy.sh"
          echo '--------------------- sl ---------------------'
          ssh ubuntu@146.56.144.121 "./deploy.sh"
          echo '--------------------- sg ---------------------'
          ssh root@172.105.204.43 "./deploy.sh"
